version: '3.8'

services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-image
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5050:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: dbuser
      POSTGRES_DB: stats

  ewm-service:
    build: main-service
    image: main-service-image
    container_name: main-service-image
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      STATS_SERVER_URL: http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "5454:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: dbuser
      POSTGRES_DB: ewm