version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    image: stats-server-image
    container_name: stats-server-image
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/evm
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=evm
  ewm-service:
    build: main-service
    image: main-service-image
    container_name: main-service-image
    ports:
      - "9090:9090"
    depends_on:
    - ewm-db
  ewm-db:
    image: postgres:14-alpine