DROP TABLE IF EXISTS requests;

CREATE TABLE IF NOT EXISTS requests(
id  BIGINT  GENERATED ALWAYS AS IDENTITY,
app VARCHAR(300),
uri VARCHAR(300),
ip  VARCHAR(15),
timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now());